import React, { useState, useEffect } from 'react';
import { useAuth } from '../../context/AuthContext';
import { meApi } from '../../api';
import { Payslip } from '../../types';
import { getMonthName } from '../../utils/dateUtils';
import {
  FileText,
  Download,
  Lock,
  Eye,
  CheckCircle2,
  ShieldCheck,
  Building2,
  AlertCircle,
  Printer
} from 'lucide-react';
import { StatusPill } from '../common/StatusPill';
import { Modal } from '../common/Modal';
import { SkeletonLoader } from '../common/SkeletonLoader';

export const MyPayslips: React.FC = () => {
  const { currentUser, showToast } = useAuth();
  const [loading, setLoading] = useState(true);
  const [year, setYear] = useState(2026);
  const [payslipsList, setPayslipsList] = useState<Array<Pick<Payslip, 'id' | 'year' | 'month' | 'source' | 'status' | 'publishedAt'>>>([]);
  const [activePayslipDoc, setActivePayslipDoc] = useState<Payslip | null>(null);
  const [viewingId, setViewingId] = useState<number | null>(null);

  const fetchPayslips = async () => {
    try {
      setLoading(true);
      const data = await meApi.getPayslips(year);
      setPayslipsList(data);
    } catch (err: any) {
      showToast('Error', err.message || 'Failed to load payslips', 'error');
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchPayslips();
  }, [year, currentUser]);

  const handleOpenPayslip = async (id: number) => {
    setViewingId(id);
    try {
      const doc = await meApi.getPayslipDocument(id);
      setActivePayslipDoc(doc);
      showToast('Access Logged', 'Payslip retrieved. Immutable audit record created for Accounts compliance.', 'info');
    } catch (err: any) {
      showToast('Access Denied', err.message || 'Unable to open payslip', 'error');
    } finally {
      setViewingId(null);
    }
  };

  const numberToWords = (num: number): string => {
    // Simple INR converter for clean payslip display
    if (num <= 0) return 'Zero';
    const a = ['', 'One', 'Two', 'Three', 'Four', 'Five', 'Six', 'Seven', 'Eight', 'Nine', 'Ten', 'Eleven', 'Twelve', 'Thirteen', 'Fourteen', 'Fifteen', 'Sixteen', 'Seventeen', 'Eighteen', 'Nineteen'];
    const b = ['', '', 'Twenty', 'Thirty', 'Forty', 'Fifty', 'Sixty', 'Seventy', 'Eighty', 'Ninety'];
    
    const inWords = (n: number): string => {
      if (n < 20) return a[n];
      if (n < 100) return b[Math.floor(n / 10)] + (n % 10 !== 0 ? ' ' + a[n % 10] : '');
      if (n < 1000) return a[Math.floor(n / 100)] + ' Hundred' + (n % 100 !== 0 ? ' ' + inWords(n % 100) : '');
      if (n < 100000) return inWords(Math.floor(n / 1000)) + ' Thousand' + (n % 1000 !== 0 ? ' ' + inWords(n % 1000) : '');
      if (n < 10000000) return inWords(Math.floor(n / 100000)) + ' Lakh' + (n % 100000 !== 0 ? ' ' + inWords(n % 100000) : '');
      return inWords(Math.floor(n / 10000000)) + ' Crore' + (n % 10000000 !== 0 ? ' ' + inWords(n % 10000000) : '');
    };
    return inWords(num) + ' Rupees Only';
  };

  return (
    <div className="p-4 sm:p-6 max-w-7xl mx-auto space-y-6">
      {/* Header */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 bg-white p-5 rounded-xl border border-slate-200 shadow-xs">
        <div>
          <div className="flex items-center gap-2">
            <h1 className="text-xl font-bold text-slate-900">Confidential Salary Slips</h1>
            <span className="text-xs px-2 py-0.5 rounded font-bold bg-amber-50 text-amber-800 border border-amber-200 flex items-center gap-1">
              <Lock className="w-3 h-3" /> Encrypted Vault
            </span>
          </div>
          <p className="text-xs text-slate-500 mt-1">
            Official monthly compensation receipts generated by Accounts Department
          </p>
        </div>

        {/* Year filter */}
        <div className="flex items-center gap-2">
          <label className="text-xs font-semibold text-slate-600">Financial Year:</label>
          <select
            value={year}
            onChange={e => setYear(Number(e.target.value))}
            className="text-xs p-2 rounded-lg border border-slate-300 font-bold bg-white text-slate-800 focus:outline-none focus:ring-1 focus:ring-teal-700"
          >
            <option value={2026}>2026</option>
            <option value={2025}>2025</option>
          </select>
        </div>
      </div>

      {/* Security notice */}
      <div className="p-3 rounded-lg bg-teal-50/70 border border-teal-200 text-xs text-teal-900 flex items-center justify-between">
        <div className="flex items-center gap-2">
          <ShieldCheck className="w-4 h-4 text-teal-700 flex-shrink-0" />
          <span>
            <strong>Zero-Knowledge List:</strong> Amounts are not rendered in the summary table to prevent shoulder-surfing. Every document access is immutably timestamped in the audit vault.
          </span>
        </div>
      </div>

      {/* Table of Payslips */}
      {loading ? (
        <SkeletonLoader type="table" rows={4} />
      ) : payslipsList.length === 0 ? (
        <div className="bg-white p-12 text-center rounded-xl border border-slate-200 shadow-xs">
          <FileText className="w-10 h-10 text-slate-300 mx-auto mb-2" />
          <h3 className="text-sm font-bold text-slate-800">No Published Payslips for {year}</h3>
          <p className="text-xs text-slate-500 mt-1">
            Accounts publishes payslips between the 1st and 5th of each calendar month.
          </p>
        </div>
      ) : (
        <div className="bg-white rounded-xl border border-slate-200 overflow-hidden shadow-xs">
          <div className="overflow-x-auto">
            <table className="w-full text-left text-xs text-slate-700">
              <thead className="bg-slate-50 border-b border-slate-200 text-slate-600 uppercase tracking-wider text-[11px] font-bold">
                <tr>
                  <th className="px-5 py-3.5">Month / Year</th>
                  <th className="px-5 py-3.5">Document Origin</th>
                  <th className="px-5 py-3.5">Publication Status</th>
                  <th className="px-5 py-3.5">Published Date</th>
                  <th className="px-5 py-3.5 text-right">Encrypted Action</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-slate-100">
                {payslipsList.map(slip => (
                  <tr key={slip.id} className="hover:bg-slate-50/80 transition-colors">
                    <td className="px-5 py-4 font-bold text-slate-900">
                      {getMonthName(slip.month)} {slip.year}
                    </td>
                    <td className="px-5 py-4">
                      <span className="text-xs font-mono font-medium px-2 py-0.5 rounded bg-slate-100 text-slate-700">
                        {slip.source === 'GENERATED' ? 'System Engine (Spring/DB)' : 'Accounts Bulk PDF'}
                      </span>
                    </td>
                    <td className="px-5 py-4">
                      <StatusPill status={slip.status} />
                    </td>
                    <td className="px-5 py-4 text-slate-500 font-mono">
                      {slip.publishedAt ? new Date(slip.publishedAt).toLocaleDateString('en-GB') : '—'}
                    </td>
                    <td className="px-5 py-4 text-right">
                      <button
                        onClick={() => handleOpenPayslip(slip.id)}
                        disabled={viewingId === slip.id}
                        className="px-3.5 py-1.5 text-xs font-semibold rounded-lg bg-teal-700 text-white hover:bg-teal-800 transition-colors inline-flex items-center gap-1.5 shadow-xs"
                      >
                        <Eye className="w-3.5 h-3.5" />
                        {viewingId === slip.id ? 'Decrypting...' : 'View & Download'}
                      </button>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>
      )}

      {/* Official Payslip Document Modal */}
      {activePayslipDoc && (
        <Modal
          isOpen={!!activePayslipDoc}
          onClose={() => setActivePayslipDoc(null)}
          title={`Official Salary Statement: ${getMonthName(activePayslipDoc.month)} ${activePayslipDoc.year}`}
          subtitle={`Confidential to ${activePayslipDoc.employeeName} (${activePayslipDoc.employeeCode})`}
          maxWidth="2xl"
        >
          <div className="space-y-6 print:p-0">
            {/* Payslip Header with Company Branding */}
            <div className="border-b border-slate-300 pb-4 flex items-start justify-between">
              <div>
                <div className="flex items-center gap-2">
                  <span className="font-bold text-lg text-teal-800 tracking-tight">SECOND MEDIC</span>
                  <span className="text-[10px] uppercase font-bold text-slate-500 border border-slate-300 px-1 rounded">
                    Healthcare
                  </span>
                </div>
                <div className="text-[11px] text-slate-600 mt-1 font-medium leading-tight">
                  SecondMedic Health Services Pvt Ltd
                </div>
                <div className="text-[10px] text-slate-400">
                  CIN: U85110PN2020PTC192841 • Baner Bio-Tech Park, Pune - 411045
                </div>
              </div>
              <div className="text-right">
                <span className="text-xs font-bold uppercase text-slate-700 block">
                  Payslip for {getMonthName(activePayslipDoc.month).toUpperCase()} {activePayslipDoc.year}
                </span>
                <span className="text-[10px] font-mono text-slate-500">
                  Ref: {activePayslipDoc.employeeCode}-{activePayslipDoc.year}-{String(activePayslipDoc.month).padStart(2, '0')}
                </span>
              </div>
            </div>

            {/* Employee Metadata Matrix */}
            <div className="grid grid-cols-2 sm:grid-cols-4 gap-3 text-xs bg-slate-50 p-3 rounded-lg border border-slate-200">
              <div>
                <span className="text-slate-400 text-[10px] block">Employee Name</span>
                <span className="font-bold text-slate-900">{activePayslipDoc.employeeName}</span>
              </div>
              <div>
                <span className="text-slate-400 text-[10px] block">Employee Code</span>
                <span className="font-bold text-slate-900 font-mono">{activePayslipDoc.employeeCode}</span>
              </div>
              <div>
                <span className="text-slate-400 text-[10px] block">Designation</span>
                <span className="font-medium text-slate-800">{activePayslipDoc.designation}</span>
              </div>
              <div>
                <span className="text-slate-400 text-[10px] block">Department</span>
                <span className="font-medium text-slate-800">{activePayslipDoc.departmentName}</span>
              </div>
              <div>
                <span className="text-slate-400 text-[10px] block">PAN Number</span>
                <span className="font-mono font-medium text-slate-800">{activePayslipDoc.panNumber || 'ABCDE1234F'}</span>
              </div>
              <div>
                <span className="text-slate-400 text-[10px] block">Bank Account</span>
                <span className="font-mono text-slate-800">{activePayslipDoc.bankAccount || 'HDFC Bank - 5010049281'}</span>
              </div>
              <div>
                <span className="text-slate-400 text-[10px] block">Paid Days</span>
                <span className="font-bold text-slate-900">{activePayslipDoc.paidDays} Days</span>
              </div>
              <div>
                <span className="text-slate-400 text-[10px] block">Loss of Pay (LOP)</span>
                <span className="font-bold text-rose-700">{activePayslipDoc.lopDays} Days</span>
              </div>
            </div>

            {/* Earnings & Deductions Table */}
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-4 text-xs">
              {/* Earnings */}
              <div className="border border-slate-200 rounded-lg overflow-hidden">
                <div className="bg-slate-100 font-bold px-3 py-2 text-slate-800 flex justify-between border-b border-slate-200">
                  <span>Earnings (A)</span>
                  <span>Amount (INR)</span>
                </div>
                <div className="divide-y divide-slate-100">
                  <div className="px-3 py-2 flex justify-between">
                    <span className="text-slate-600">Basic Salary</span>
                    <span className="font-mono font-medium">₹{activePayslipDoc.components.basic.toLocaleString('en-IN')}</span>
                  </div>
                  <div className="px-3 py-2 flex justify-between">
                    <span className="text-slate-600">House Rent Allowance (HRA)</span>
                    <span className="font-mono font-medium">₹{activePayslipDoc.components.hra.toLocaleString('en-IN')}</span>
                  </div>
                  <div className="px-3 py-2 flex justify-between">
                    <span className="text-slate-600">Special / Medical Allowance</span>
                    <span className="font-mono font-medium">₹{activePayslipDoc.components.specialAllowance.toLocaleString('en-IN')}</span>
                  </div>
                  <div className="px-3 py-2 bg-slate-50 font-bold text-slate-900 flex justify-between border-t border-slate-200">
                    <span>Gross Earnings</span>
                    <span className="font-mono text-teal-800">₹{activePayslipDoc.grossAmount.toLocaleString('en-IN')}</span>
                  </div>
                </div>
              </div>

              {/* Deductions */}
              <div className="border border-slate-200 rounded-lg overflow-hidden">
                <div className="bg-slate-100 font-bold px-3 py-2 text-slate-800 flex justify-between border-b border-slate-200">
                  <span>Deductions (B)</span>
                  <span>Amount (INR)</span>
                </div>
                <div className="divide-y divide-slate-100">
                  <div className="px-3 py-2 flex justify-between">
                    <span className="text-slate-600">Provident Fund (PF)</span>
                    <span className="font-mono font-medium">₹{activePayslipDoc.components.pf.toLocaleString('en-IN')}</span>
                  </div>
                  <div className="px-3 py-2 flex justify-between">
                    <span className="text-slate-600">Professional Tax (PT)</span>
                    <span className="font-mono font-medium">₹{activePayslipDoc.components.pt.toLocaleString('en-IN')}</span>
                  </div>
                  <div className="px-3 py-2 flex justify-between">
                    <span className="text-slate-600">Income Tax (TDS)</span>
                    <span className="font-mono font-medium">₹{activePayslipDoc.components.tds.toLocaleString('en-IN')}</span>
                  </div>
                  {activePayslipDoc.components.lopDeduction > 0 && (
                    <div className="px-3 py-2 flex justify-between text-rose-700 bg-rose-50/50">
                      <span>LOP Deduction ({activePayslipDoc.lopDays} days)</span>
                      <span className="font-mono font-medium">₹{activePayslipDoc.components.lopDeduction.toLocaleString('en-IN')}</span>
                    </div>
                  )}
                  <div className="px-3 py-2 bg-slate-50 font-bold text-slate-900 flex justify-between border-t border-slate-200">
                    <span>Total Deductions</span>
                    <span className="font-mono text-rose-800">₹{activePayslipDoc.totalDeductions.toLocaleString('en-IN')}</span>
                  </div>
                </div>
              </div>
            </div>

            {/* Net Pay Bar */}
            <div className="p-4 rounded-xl bg-teal-900 text-white flex flex-col sm:flex-row sm:items-center justify-between gap-3 shadow-md">
              <div>
                <span className="text-[10px] uppercase tracking-wider text-teal-300 font-bold">
                  Net Salary Payable (A - B)
                </span>
                <div className="text-2xl font-extrabold font-mono mt-0.5">
                  ₹{activePayslipDoc.netAmount.toLocaleString('en-IN')}
                </div>
                <div className="text-[11px] text-teal-200 mt-1 italic">
                  In Words: {numberToWords(activePayslipDoc.netAmount)}
                </div>
              </div>
              <div className="text-right text-[11px] text-teal-300 sm:border-l sm:border-teal-800 sm:pl-4">
                <div className="flex items-center gap-1.5 justify-end">
                  <ShieldCheck className="w-4 h-4 text-teal-400" />
                  <span className="font-mono font-bold">Accounts Signed</span>
                </div>
                <div className="text-[10px] text-teal-400/80 font-mono mt-0.5">
                  Sha256: {activePayslipDoc.fileSha256 ? activePayslipDoc.fileSha256.substring(0, 16) + '...' : 'Signed'}
                </div>
              </div>
            </div>

            {/* Print / Close Footer */}
            <div className="flex items-center justify-between pt-2 border-t border-slate-200 text-xs">
              <span className="text-[10px] text-slate-400">
                This is a computer-generated document requiring no physical signature.
              </span>
              <div className="flex items-center gap-2">
                <button
                  type="button"
                  onClick={() => window.print()}
                  className="px-3 py-1.5 rounded-lg border border-slate-300 text-slate-700 hover:bg-slate-100 flex items-center gap-1.5 font-medium"
                >
                  <Printer className="w-3.5 h-3.5" /> Print
                </button>
                <button
                  type="button"
                  onClick={() => setActivePayslipDoc(null)}
                  className="px-4 py-1.5 rounded-lg bg-teal-700 text-white hover:bg-teal-800 font-semibold"
                >
                  Done
                </button>
              </div>
            </div>
          </div>
        </Modal>
      )}
    </div>
  );
};
